
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------

local tableConcat = table.concat
local ipairs = ipairs
local pairs = pairs

local enums =
{
    ---@class EChatSendType @聊天发送类型
    EChatSendType = { 
    -- *  发送给自己
    Owner=1,
    -- *  发送给全服
    All=2,
    -- *  发送给行会
    Guild=3,
    -- *  发送给地图
    Map=4,
    -- *  发送给队伍
    Team=5,
    };

    ---@class EChatSendType_Desc
    EChatSendType_Desc = { 
    [1]={ "Owner", "发送给自己" },
    [2]={ "All", "发送给全服" },
    [3]={ "Guild", "发送给行会" },
    [4]={ "Map", "发送给地图" },
    [5]={ "Team", "发送给队伍" },
    };

    ---@class EEventIDC @客户端事件ID
    EEventIDC = { 
    -- *  无效
    Invalid=0,
    -- *  匹配状态刷新
    Match_Status_Refresh=1000,
    -- *  匹配成功
    Match_Success=1001,
    };

    ---@class EEventIDC_Desc
    EEventIDC_Desc = { 
    [0]={ "Invalid", "无效" },
    [1000]={ "Match_Status_Refresh", "匹配状态刷新" },
    [1001]={ "Match_Success", "匹配成功" },
    };

    ---@class EEventIDS @服务器事件ID
    EEventIDS = { 
    -- *  无效
    Invalid=0,
    -- *  玩家登录
    Player_Login=1000,
    -- *  玩家跨天登录
    Player_CrossDayLogin=1001,
    -- *  玩家每天首次登录
    Player_DailyFirstLogin=1002,
    -- *  玩家死亡
    Player_Die=1003,
    -- *  玩家进入地图
    Map_Enter=2000,
    -- *  玩家离开地图
    Map_Leave=2001,
    };

    ---@class EEventIDS_Desc
    EEventIDS_Desc = { 
    [0]={ "Invalid", "无效" },
    [1000]={ "Player_Login", "玩家登录" },
    [1001]={ "Player_CrossDayLogin", "玩家跨天登录" },
    [1002]={ "Player_DailyFirstLogin", "玩家每天首次登录" },
    [1003]={ "Player_Die", "玩家死亡" },
    [2000]={ "Map_Enter", "玩家进入地图" },
    [2001]={ "Map_Leave", "玩家离开地图" },
    };

    ---@class EObjectInfoID @对象信息ID
    EObjectInfoID = { 
    -- *  是否是玩家，返回boolean，true=玩家
    IsPlayer=-1,
    -- *  是否死亡，返回bool，true=死亡
    IsDie=0,
    -- *  名字，返回string，当对象为怪物时，param3=0/nil，返回怪物显示名(即去除了尾部的数字)，param3=1时返回怪物默认名(怪物表中配置的名字)，param3=2时返回怪物实际名
    Name=1,
    -- *  唯一ID，返回string
    ID=2,
    -- *  当前地图ID，返回string
    MapID=3,
    -- *  当前X坐标，返回integer
    X=4,
    -- *  当前Y坐标，返回integer
    Y=5,
    -- *  等级，返回integer
    Level=6,
    -- *  职业，返回integer，0=战士，1=法师，2=道士
    Job=7,
    -- *  性别，返回integer
    Gender=8,
    -- *  当前血量，返回integer
    CurrHP=9,
    -- *  最大血量，返回integer
    MaxHP=10,
    -- *  当前魔法，返回integer
    CurrMP=11,
    -- *  最大魔法，返回integer
    MaxMP=12,
    -- *  当前经验，返回integer
    CurrExp=13,
    -- *  最大经验，返回integer
    MaxExp=14,
    -- *  物理防御下限，返回integer
    PhysicalDefendMin=15,
    -- *  物理防御上限，返回integer
    PhysicalDefendMax=16,
    -- *  魔法防御下限，返回integer
    MagicDefendMin=17,
    -- *  魔法防御上限，返回integer
    MagicDefendMax=18,
    -- *  物理攻击下限，返回integer
    PhysicalAttackMin=19,
    -- *  物理攻击上限，返回integer
    PhysicalAttackMax=20,
    -- *  魔法攻击下限，返回integer
    MagicAttackMin=21,
    -- *  魔法攻击上限，返回integer
    MagicAttackMax=22,
    -- *  道术攻击下限，返回integer
    DaoisticAttackMin=23,
    -- *  道术攻击上限，返回integer
    DaoisticAttackMax=24,
    -- *  幸运值，返回integer
    LuckValue=25,
    -- *  血量恢复，返回integer
    HPRecover=26,
    -- *  魔法恢复，返回integer
    MPRecover=27,
    -- *  中毒恢复，返回integer
    PoisoningRecover=28,
    -- *  中毒闪避，返回integer
    PoisoningDodge=29,
    -- *  魔法闪避，返回integer
    MagicDodge=30,
    -- *  命中率，返回integer，无法设置
    HitRate=31,
    -- *  敏捷，返回integer
    Dexterity=32,
    -- *  发型，返回integer
    Hair=33,
    -- *  背包物品数量，返回integer，仅玩家有效
    BagItemCount=34,
    -- *  队伍成员数量，返回integer，仅玩家有效
    TeamMemberCount=35,
    -- *  公会名，返回string，仅玩家有效
    GuildName=36,
    -- *  是否是公会会长，返回bool，true=是公会会长，仅玩家有效
    IsGuildLeader=37,
    -- *  宠物数量，返回integer
    PetCount=38,
    -- *  转生等级，返回integer
    RebornLevel=39,
    -- *  击杀怪物经验倍率，返回integer
    KillMonsterExpRate=40,
    -- *  击杀怪物经验倍率剩余时间，返回integer
    KillMonsterExpTime=41,
    -- *  显示延时TIMERECALL还剩多少秒(仅人物)
    ShowTimerCallLast=42,
    -- *  杀怪爆率倍数，返回integer，仅玩家有效
    KillMonsterDropRate=43,
    -- *  复活时间，返回integer
    ReviveTime=44,
    -- *  地图名MAPTITLE，返回string
    mapName=45,
    -- *  PK点数，返回integer
    PKPoint=46,
    -- *  是否新手，返回bool，true=新手，仅玩家有效
    IsNewPlayer=47,
    -- *  是否安全区
    SafeArena=48,
    -- *  是否摆摊中，返回bool，true=摆摊中，仅玩家有效
    IsStall=49,
    -- *  是否交易中，返回bool，true=交易中，仅玩家有效
    IsDeal=50,
    -- *  att属性值，需要提供 参数3:属性ID(cfg_att_score.xls设置：1~129，200~249)自定义属性在24.0807引擎拓展到200~399
    Attr=51,
    -- *  穿人/怪方式 0=恢复/1=穿人/2=穿怪/3=穿人穿怪
    ThroughType=52,
    -- *  登录状态，0：正常，1：断线重连(仅人物)
    LoginStatus=53,
    -- *  主人UserId
    MasterID=54,
    -- *  Idx
    Index=55,
    -- *  颜色(0~255)
    Color=56,
    -- *  最后杀死的怪物Index(仅人物)
    FinalKillMonsterIndex=57,
    -- *  时装显示状态(仅人物)
    FashionShow=58,
    -- *  主人对象
    MasterObject=59,
    -- *  是否攻城状态
    IsCastleWar=60,
    -- *  是否离线挂机状态
    IsOfflineFight=61,
    -- *  获取怪物表自定义常量(25列)
    ID62=62,
    -- *  背包格子数，返回integer，仅玩家有效
    BagSize=63,
    -- *  获取对象当前的身体颜色值
    ID64=64,
    -- *  对象的回城地图
    BackMapID=65,
    -- *  官方没有定义
    ID66=66,
    -- *  攻击对象
    AttackObject=67,
    -- *  怪物归属对象
    ID68=68,
    -- *  获取对象当前的方向(新增于引擎64_23.08.30)
    Dir=69,
    };

    ---@class EObjectInfoID_Desc
    EObjectInfoID_Desc = { 
    [-1]={ "IsPlayer", "是否是玩家，返回boolean，true=玩家" },
    [0]={ "IsDie", "是否死亡，返回bool，true=死亡" },
    [1]={ "Name", "名字，返回string，当对象为怪物时，param3=0/nil，返回怪物显示名(即去除了尾部的数字)，param3=1时返回怪物默认名(怪物表中配置的名字)，param3=2时返回怪物实际名" },
    [2]={ "ID", "唯一ID，返回string" },
    [3]={ "MapID", "当前地图ID，返回string" },
    [4]={ "X", "当前X坐标，返回integer" },
    [5]={ "Y", "当前Y坐标，返回integer" },
    [6]={ "Level", "等级，返回integer" },
    [7]={ "Job", "职业，返回integer，0=战士，1=法师，2=道士" },
    [8]={ "Gender", "性别，返回integer" },
    [9]={ "CurrHP", "当前血量，返回integer" },
    [10]={ "MaxHP", "最大血量，返回integer" },
    [11]={ "CurrMP", "当前魔法，返回integer" },
    [12]={ "MaxMP", "最大魔法，返回integer" },
    [13]={ "CurrExp", "当前经验，返回integer" },
    [14]={ "MaxExp", "最大经验，返回integer" },
    [15]={ "PhysicalDefendMin", "物理防御下限，返回integer" },
    [16]={ "PhysicalDefendMax", "物理防御上限，返回integer" },
    [17]={ "MagicDefendMin", "魔法防御下限，返回integer" },
    [18]={ "MagicDefendMax", "魔法防御上限，返回integer" },
    [19]={ "PhysicalAttackMin", "物理攻击下限，返回integer" },
    [20]={ "PhysicalAttackMax", "物理攻击上限，返回integer" },
    [21]={ "MagicAttackMin", "魔法攻击下限，返回integer" },
    [22]={ "MagicAttackMax", "魔法攻击上限，返回integer" },
    [23]={ "DaoisticAttackMin", "道术攻击下限，返回integer" },
    [24]={ "DaoisticAttackMax", "道术攻击上限，返回integer" },
    [25]={ "LuckValue", "幸运值，返回integer" },
    [26]={ "HPRecover", "血量恢复，返回integer" },
    [27]={ "MPRecover", "魔法恢复，返回integer" },
    [28]={ "PoisoningRecover", "中毒恢复，返回integer" },
    [29]={ "PoisoningDodge", "中毒闪避，返回integer" },
    [30]={ "MagicDodge", "魔法闪避，返回integer" },
    [31]={ "HitRate", "命中率，返回integer，无法设置" },
    [32]={ "Dexterity", "敏捷，返回integer" },
    [33]={ "Hair", "发型，返回integer" },
    [34]={ "BagItemCount", "背包物品数量，返回integer，仅玩家有效" },
    [35]={ "TeamMemberCount", "队伍成员数量，返回integer，仅玩家有效" },
    [36]={ "GuildName", "公会名，返回string，仅玩家有效" },
    [37]={ "IsGuildLeader", "是否是公会会长，返回bool，true=是公会会长，仅玩家有效" },
    [38]={ "PetCount", "宠物数量，返回integer" },
    [39]={ "RebornLevel", "转生等级，返回integer" },
    [40]={ "KillMonsterExpRate", "击杀怪物经验倍率，返回integer" },
    [41]={ "KillMonsterExpTime", "击杀怪物经验倍率剩余时间，返回integer" },
    [42]={ "ShowTimerCallLast", "显示延时TIMERECALL还剩多少秒(仅人物)" },
    [43]={ "KillMonsterDropRate", "杀怪爆率倍数，返回integer，仅玩家有效" },
    [44]={ "ReviveTime", "复活时间，返回integer" },
    [45]={ "mapName", "地图名MAPTITLE，返回string" },
    [46]={ "PKPoint", "PK点数，返回integer" },
    [47]={ "IsNewPlayer", "是否新手，返回bool，true=新手，仅玩家有效" },
    [48]={ "SafeArena", "是否安全区" },
    [49]={ "IsStall", "是否摆摊中，返回bool，true=摆摊中，仅玩家有效" },
    [50]={ "IsDeal", "是否交易中，返回bool，true=交易中，仅玩家有效" },
    [51]={ "Attr", "att属性值，需要提供 参数3:属性ID(cfg_att_score.xls设置：1~129，200~249)自定义属性在24.0807引擎拓展到200~399" },
    [52]={ "ThroughType", "穿人/怪方式 0=恢复/1=穿人/2=穿怪/3=穿人穿怪" },
    [53]={ "LoginStatus", "登录状态，0：正常，1：断线重连(仅人物)" },
    [54]={ "MasterID", "主人UserId" },
    [55]={ "Index", "Idx" },
    [56]={ "Color", "颜色(0~255)" },
    [57]={ "FinalKillMonsterIndex", "最后杀死的怪物Index(仅人物)" },
    [58]={ "FashionShow", "时装显示状态(仅人物)" },
    [59]={ "MasterObject", "主人对象" },
    [60]={ "IsCastleWar", "是否攻城状态" },
    [61]={ "IsOfflineFight", "是否离线挂机状态" },
    [62]={ "ID62", "获取怪物表自定义常量(25列)" },
    [63]={ "BagSize", "背包格子数，返回integer，仅玩家有效" },
    [64]={ "ID64", "获取对象当前的身体颜色值" },
    [65]={ "BackMapID", "对象的回城地图" },
    [66]={ "ID66", "官方没有定义" },
    [67]={ "AttackObject", "攻击对象" },
    [68]={ "ID68", "怪物归属对象" },
    [69]={ "Dir", "获取对象当前的方向(新增于引擎64_23.08.30)" },
    };

    ---@class EPKModelType @PK模型类型
    EPKModelType = { 
    -- *  全体模式
    All=0,
    -- *  和平模式
    Peace=1,
    -- *  夫妻模式
    Couple=2,
    -- *  师徒模式
    Master=3,
    -- *  组队模式
    Team=4,
    -- *  行会模式
    Guild=5,
    -- *  红名模式
    RedName=6,
    -- *  国家模式
    Country=7,
    };

    ---@class EPKModelType_Desc
    EPKModelType_Desc = { 
    [0]={ "All", "全体模式" },
    [1]={ "Peace", "和平模式" },
    [2]={ "Couple", "夫妻模式" },
    [3]={ "Master", "师徒模式" },
    [4]={ "Team", "组队模式" },
    [5]={ "Guild", "行会模式" },
    [6]={ "RedName", "红名模式" },
    [7]={ "Country", "国家模式" },
    };

}

---@class GameMisc.LubanBean
local beans = {}

local tables =
{
}

-- * 组合key
---@param tKey table 可变参数
---@return string
local function combineKey(tKey)
    return "key_"..tableConcat(tKey, "_")
end

-- * 解析表格
local function parseTable(t, keys, srcDatas)
    t.AllTables = {}
    t.AllKeys = {}

    for _, data in pairs(srcDatas) do
        local tKey = {}
        for _, k in ipairs(keys) do
            tKey[#tKey + 1] = data[k]
        end
        local key = combineKey(tKey)
        t.AllKeys[key] = #t.AllTables + 1
        t.AllTables[t.AllKeys[key]] = data
    end
end

-- * 创建全部表格
---@param require function
---@return table 全部数据表格
local function createAllTables(require)
    ---@class GameMisc.AllTables
    local allTables = {}


    return allTables
end

return { enums = enums, beans = beans, tables = tables, createAllTables = createAllTables }

