
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------

local tableConcat = table.concat
local ipairs = ipairs
local pairs = pairs

local enums =
{
    ---@class EFuncId @功能Id
    EFuncId = { 
    -- * 无效
    Invalid=0,
    -- * 匹配
    Match=1,
    };

    ---@class EFuncId_Desc
    EFuncId_Desc = { 
    [0]={ "Invalid", "无效" },
    [1]={ "Match", "匹配" },
    };

    ---@class EMatchMode @匹配模式
    EMatchMode = { 
    -- * 无匹配模式
    None=0,
    -- * 普通模式
    Normal=1,
    -- * 排位模式
    Rank=2,
    };

    ---@class EMatchMode_Desc
    EMatchMode_Desc = { 
    [0]={ "None", "无匹配模式" },
    [1]={ "Normal", "普通模式" },
    [2]={ "Rank", "排位模式" },
    };

    ---@class ENoticeId @提示Id
    ENoticeId = { 
    -- * 成功
    Success=0,
    -- * 未知错误
    Error_Unknown=1,
    -- * 无效玩家
    Error_InvalidPlayer=2,
    -- * JSON解析错误
    Error_JsonParseError=3,
    -- * 匹配成功
    Match_Success=10000,
    -- * 匹配失败
    Match_Failed=10001,
    -- * 已匹配成功
    Match_AlreadySuccess=10002,
    -- * 已在匹配队列
    Match_Already=10003,
    -- * 不在匹配队列
    Match_NoInList=10004,
    -- * 匹配模式不存在
    Match_ModeNotExist=10005,
    -- * 取消匹配成功
    Match_CancelSuccess=10006,
    };

    ---@class ENoticeId_Desc
    ENoticeId_Desc = { 
    [0]={ "Success", "成功" },
    [1]={ "Error_Unknown", "未知错误" },
    [2]={ "Error_InvalidPlayer", "无效玩家" },
    [3]={ "Error_JsonParseError", "JSON解析错误" },
    [10000]={ "Match_Success", "匹配成功" },
    [10001]={ "Match_Failed", "匹配失败" },
    [10002]={ "Match_AlreadySuccess", "已匹配成功" },
    [10003]={ "Match_Already", "已在匹配队列" },
    [10004]={ "Match_NoInList", "不在匹配队列" },
    [10005]={ "Match_ModeNotExist", "匹配模式不存在" },
    [10006]={ "Match_CancelSuccess", "取消匹配成功" },
    };

    ---@class ENPCFuncType @NPC功能类型
    ENPCFuncType = { 
    -- * 无效
    Invalid=0,
    -- * 打开界面
    OpenView=1,
    };

    ---@class ENPCFuncType_Desc
    ENPCFuncType_Desc = { 
    [0]={ "Invalid", "无效" },
    [1]={ "OpenView", "打开界面" },
    };

    ---@class EOperateId @操作Id
    EOperateId = { 
    -- * 无效
    Invalid=0,
    -- * 请求匹配
    Match_ReqMatch=1000,
    -- * 取消匹配
    Match_CancelMatch=1001,
    };

    ---@class EOperateId_Desc
    EOperateId_Desc = { 
    [0]={ "Invalid", "无效" },
    [1000]={ "Match_ReqMatch", "请求匹配" },
    [1001]={ "Match_CancelMatch", "取消匹配" },
    };

    ---@class EPlayerDetailState @玩家详细状态，除100，向下取整则为 EPlayerState 的值
    EPlayerDetailState = { 
    -- * 未知
    Unknown=-1,
    -- * 常规状态
    Normal=0,
    -- * 匹配中
    Matching=100,
    -- * 匹配成功等待进入
    Match_Success=101,
    -- * 战斗中
    Battle_Fight=200,
    -- * 战斗死亡，未结算
    Battle_Dead=201,
    -- * 战斗已结算
    Battle_Settlement=202,
    };

    ---@class EPlayerDetailState_Desc
    EPlayerDetailState_Desc = { 
    [-1]={ "Unknown", "未知" },
    [0]={ "Normal", "常规状态" },
    [100]={ "Matching", "匹配中" },
    [101]={ "Match_Success", "匹配成功等待进入" },
    [200]={ "Battle_Fight", "战斗中" },
    [201]={ "Battle_Dead", "战斗死亡，未结算" },
    [202]={ "Battle_Settlement", "战斗已结算" },
    };

    ---@class EPlayerState @玩家状态
    EPlayerState = { 
    -- * 常规状态
    Normal=0,
    -- * 匹配状态
    Match=1,
    -- * 战场状态
    Battle=2,
    };

    ---@class EPlayerState_Desc
    EPlayerState_Desc = { 
    [0]={ "Normal", "常规状态" },
    [1]={ "Match", "匹配状态" },
    [2]={ "Battle", "战场状态" },
    };

    ---@class ESkillTriggerEffect @触发效果
    ESkillTriggerEffect = { 
    -- * 无效果
    None=0,
    -- * 替换技能 参数 替换后的技能Id
    ReplaceSkill=1,
    -- * 使用技能 参数 使用的技能Id
    UseSkill=2,
    };

    ---@class ESkillTriggerEffect_Desc
    ESkillTriggerEffect_Desc = { 
    [0]={ "None", "无效果" },
    [1]={ "ReplaceSkill", "参数 替换后的技能Id" },
    [2]={ "UseSkill", "参数 使用的技能Id" },
    };

    ---@class ESkillTriggerStage @触发阶段
    ESkillTriggerStage = { 
    -- * 无效 无效阶段
    Invalid=0,
    -- * 使用技能前 对应996函数 beginmagic, magselffunc 在它之前
    UseBefore=1,
    -- * 自身使用技能 对应996函数 magselffunc
    Use=2,
    -- * 对目标人物使用技能 对应996函数 magtagfunc
    UseTarget=3,
    -- * 对目标怪物使用技能 对应996函数 magmonfunc
    UseMonster=4,
    -- * 推动技能使用前 对应996函数 canpush
    PushUseBefore=5,
    -- * 自定义技能处理伤害前 对应996函数 custommagicdamage
    CustomDamageBefore=6,
    -- * 暴击伤害 对应996函数 crittrigger
    CritDamage=7,
    -- * 伤害反弹伤害 对应996函数 reboundhurt
    ReboundHurt=8,
    -- * 伤害前 对应996函数 attackdamage
    DamageBefore=9,
    -- * 物理伤害后 对应996函数 attack
    PhysicalDamageAfter=10,
    -- * 魔法伤害后 对应996函数 magicattack
    MagicDamageAfter=11,
    -- * 受到伤害前 对应996函数 struckdamage
    RecDamageBefore=12,
    -- * 受到物理伤害后 对应996函数 struck 
    RecPhysicalDamageAfter=13,
    -- * 受到魔法伤害后 对应996函数 magicstruck 
    RecMagicDamageAfter=14,
    -- * 宝宝伤害前 对应996函数 attackdamagebb
    BBDamageBefore=100,
    -- * 宝宝物理伤害后 对应996函数 attackpet
    BBPhysicalDamageAfter=101,
    -- * 宝宝魔法伤害后 对应996函数 magicattackpet
    BBMagicDamageAfter=102,
    -- * 宝宝受到伤害前 对应996函数 struckdamagebb 
    BBRecDamageBefore=103,
    -- * 宝宝受到物理伤害后 对应996函数 struckpet 
    BBRecPhysicalDamageAfter=104,
    -- * 宝宝受到魔法伤害后 对应996函数 magicstruckpet 
    BBRecMagicDamageAfter=105,
    -- * 宝宝推动技能使用前 对应996函数 bbcanpush
    BBPushUseBefore=106,
    -- * 英雄伤害前 对应996函数 heroattackdamage
    HeroDamageBefore=200,
    -- * 英雄物理伤害后 对应996函数 heroattack
    HeroPhysicalDamageAfter=201,
    -- * 英雄魔法伤害后 对应996函数 heromagicattack
    HeroMagicDamageAfter=202,
    -- * 英雄受到伤害前 对应996函数 herostruckdamage 
    HeroRecDamageBefore=203,
    -- * 英雄受到物理伤害后 对应996函数 herostruck 
    HeroRecPhysicalDamageAfter=204,
    -- * 英雄受到魔法伤害后 对应996函数 heromagicstruck 
    HeroRecMagicDamageAfter=205,
    -- * 英雄使用技能前 对应996函数 herobeginmagic
    HeroUseBefore=206,
    -- * 英雄推动技能使用前 对应996函数 herocanpush
    HeroPushUseBefore=207,
    -- * 英雄宝宝伤害前 对应996函数 heroattackdamagebb
    HeroBBDamageBefore=300,
    -- * 英雄宝宝物理伤害后 对应996函数 heroattackpet
    HeroBBPhysicalDamageAfter=301,
    -- * 英雄宝宝魔法伤害后 对应996函数 heromagicattackpet
    HeroBBMagicDamageAfter=302,
    -- * 英雄宝宝受到伤害前 对应996函数 herostruckdamagebb 
    HeroBBRecDamageBefore=303,
    -- * 英雄宝宝受到物理伤害后 对应996函数 herostruckpet 
    HeroBBRecPhysicalDamageAfter=304,
    -- * 英雄宝宝受到魔法伤害后 对应996函数 heromagicstruckpet  
    HeroBBRecMagicDamageAfter=305,
    -- * 英雄宝宝推动技能使用前 对应996函数 herobbcanpush
    HeroBBPushUseBefore=306,
    -- * 宠物推动技能使用前 对应996函数 petcanpush
    PetPushUseBefore=400,
    -- * 宠物攻击 对应996函数 attackbypet
    PetAttack=401,
    -- * 宠物攻击伤害前 对应996函数 attackdamagepet
    PetDamageBefore=402,
    -- * 宠物被攻击前 对应996函数 struckdamagepet
    PetRecDamageBefore=403,
    -- * 宠物被物理攻击 对应996函数 struckofpet
    PetRecPhysicalDamageAfter=404,
    -- * 宠物被魔法攻击 对应996函数 magicstruckofpet
    PetRecMagicDamageAfter=405,
    };

    ---@class ESkillTriggerStage_Desc
    ESkillTriggerStage_Desc = { 
    [0]={ "Invalid", "无效阶段" },
    [1]={ "UseBefore", "对应996函数 beginmagic, magselffunc 在它之前" },
    [2]={ "Use", "对应996函数 magselffunc" },
    [3]={ "UseTarget", "对应996函数 magtagfunc" },
    [4]={ "UseMonster", "对应996函数 magmonfunc" },
    [5]={ "PushUseBefore", "对应996函数 canpush" },
    [6]={ "CustomDamageBefore", "对应996函数 custommagicdamage" },
    [7]={ "CritDamage", "对应996函数 crittrigger" },
    [8]={ "ReboundHurt", "对应996函数 reboundhurt" },
    [9]={ "DamageBefore", "对应996函数 attackdamage" },
    [10]={ "PhysicalDamageAfter", "对应996函数 attack" },
    [11]={ "MagicDamageAfter", "对应996函数 magicattack" },
    [12]={ "RecDamageBefore", "对应996函数 struckdamage" },
    [13]={ "RecPhysicalDamageAfter", "对应996函数 struck " },
    [14]={ "RecMagicDamageAfter", "对应996函数 magicstruck " },
    [100]={ "BBDamageBefore", "对应996函数 attackdamagebb" },
    [101]={ "BBPhysicalDamageAfter", "对应996函数 attackpet" },
    [102]={ "BBMagicDamageAfter", "对应996函数 magicattackpet" },
    [103]={ "BBRecDamageBefore", "对应996函数 struckdamagebb " },
    [104]={ "BBRecPhysicalDamageAfter", "对应996函数 struckpet " },
    [105]={ "BBRecMagicDamageAfter", "对应996函数 magicstruckpet " },
    [106]={ "BBPushUseBefore", "对应996函数 bbcanpush" },
    [200]={ "HeroDamageBefore", "对应996函数 heroattackdamage" },
    [201]={ "HeroPhysicalDamageAfter", "对应996函数 heroattack" },
    [202]={ "HeroMagicDamageAfter", "对应996函数 heromagicattack" },
    [203]={ "HeroRecDamageBefore", "对应996函数 herostruckdamage " },
    [204]={ "HeroRecPhysicalDamageAfter", "对应996函数 herostruck " },
    [205]={ "HeroRecMagicDamageAfter", "对应996函数 heromagicstruck " },
    [206]={ "HeroUseBefore", "对应996函数 herobeginmagic" },
    [207]={ "HeroPushUseBefore", "对应996函数 herocanpush" },
    [300]={ "HeroBBDamageBefore", "对应996函数 heroattackdamagebb" },
    [301]={ "HeroBBPhysicalDamageAfter", "对应996函数 heroattackpet" },
    [302]={ "HeroBBMagicDamageAfter", "对应996函数 heromagicattackpet" },
    [303]={ "HeroBBRecDamageBefore", "对应996函数 herostruckdamagebb " },
    [304]={ "HeroBBRecPhysicalDamageAfter", "对应996函数 herostruckpet " },
    [305]={ "HeroBBRecMagicDamageAfter", "对应996函数 heromagicstruckpet  " },
    [306]={ "HeroBBPushUseBefore", "对应996函数 herobbcanpush" },
    [400]={ "PetPushUseBefore", "对应996函数 petcanpush" },
    [401]={ "PetAttack", "对应996函数 attackbypet" },
    [402]={ "PetDamageBefore", "对应996函数 attackdamagepet" },
    [403]={ "PetRecDamageBefore", "对应996函数 struckdamagepet" },
    [404]={ "PetRecPhysicalDamageAfter", "对应996函数 struckofpet" },
    [405]={ "PetRecMagicDamageAfter", "对应996函数 magicstruckofpet" },
    };

}

---@class GameConfig.LubanBean
local beans = {}

---@return CfgC.BattlefieldBase
local createBattlefieldBase = function()
    ---@class CfgC.BattlefieldBase 
    ---@field public Id integer @战场模式Id
    ---@field public name string @战场名称
    ---@field public desc string @战场描述
    ---@field public MapId integer @地图Id
    ---@field public IsSingle boolean @是否单队伍，默认多队伍
    return {
        Id =0,
        name ="",
        desc ="",
        MapId =0,
        IsSingle =false,
    }
end
beans.createBattlefieldBase = createBattlefieldBase

---@return CfgC.DreamBase
local createDreamBase = function()
    ---@class CfgC.DreamBase 
    ---@field public Id integer @梦境Id
    ---@field public Name integer @梦境名称
    ---@field public Desc integer @梦境描述
    return {
        Id =0,
        Name =0,
        Desc =0,
    }
end
beans.createDreamBase = createDreamBase

---@return CfgC.Language
local createLanguage = function()
    ---@class CfgC.Language 
    ---@field public Id integer @文本Id，如果是
    ---@field public DefaultText string @默认文本
    return {
        Id =0,
        DefaultText ="",
    }
end
beans.createLanguage = createLanguage

---@return CfgC.MapBase
local createMapBase = function()
    ---@class CfgC.MapBase 
    ---@field public Id integer @地图Id
    ---@field public AssetName string @地图资源名称
    return {
        Id =0,
        AssetName ="",
    }
end
beans.createMapBase = createMapBase

---@return CfgC.NoticeText
local createNoticeText = function()
    ---@class CfgC.NoticeText 
    ---@field public Id integer @提示Id，10000以下是系统的
    ---@field public TextId integer @文本Id，见Language.xlsx
    return {
        Id =0,
        TextId =0,
    }
end
beans.createNoticeText = createNoticeText

---@return CfgC.NPCFunc
local createNPCFunc = function()
    ---@class CfgC.NPCFunc 
    ---@field public Id integer @对应的NPCId
    ---@field public FuncType integer @功能类型
    ---@field public StrParamList string[] @字符串参数列表
    return {
        Id =0,
        FuncType =0,
        StrParamList ={},
    }
end
beans.createNPCFunc = createNPCFunc

---@return Control.OperateControl
local createOperateControl = function()
    ---@class Control.OperateControl 
    ---@field public OperateId integer @操作Id
    ---@field public FuncId integer @绑定的FuncId，如果大于0，则会同时需要判断功能是否可用
    ---@field public AllowState integer[] @如果有内容表示只能这些状态下使用，否则走禁用规则
    ---@field public ForbidState integer[] @如果有内容表示这些状态下禁用
    ---@field public AllowDetailState integer[] @如果有内容表示只能这些状态下使用，否则走禁用规则
    ---@field public ForbidDetailState integer[] @如果有内容表示这些状态下禁用
    return {
        OperateId =0,
        FuncId =0,
        AllowState ={},
        ForbidState ={},
        AllowDetailState ={},
        ForbidDetailState ={},
    }
end
beans.createOperateControl = createOperateControl

---@return Func.FuncBase
local createFuncBase = function()
    ---@class Func.FuncBase 
    ---@field public FuncId integer @功能Id
    ---@field public AllowState integer[] @如果有内容表示只能这些状态下使用，否则走禁用规则
    ---@field public ForbidState integer[] @如果有内容表示这些状态下禁用
    return {
        FuncId =0,
        AllowState ={},
        ForbidState ={},
    }
end
beans.createFuncBase = createFuncBase

---@return Position
local createPosition = function()
    ---@class Position 
    ---@field public X integer
    ---@field public Y integer
    return {
        X =0,
        Y =0,
    }
end
beans.createPosition = createPosition

local tables =
{
    ["TbCMapBase"] = { name='TbCMapBase', file='cfgc_tbcmapbase', mode='map', index='Id', value_type='CfgC.MapBase' },
    ["TbCBattlefieldBase"] = { name='TbCBattlefieldBase', file='cfgc_tbcbattlefieldbase', mode='map', index='Id', value_type='CfgC.BattlefieldBase' },
    ["TbCLanguage"] = { name='TbCLanguage', file='cfgc_tbclanguage', mode='map', index='Id', value_type='CfgC.Language' },
    ["TbCNoticeText"] = { name='TbCNoticeText', file='cfgc_tbcnoticetext', mode='map', index='Id', value_type='CfgC.NoticeText' },
    ["TbCDreamBase"] = { name='TbCDreamBase', file='cfgc_tbcdreambase', mode='list', index='', value_type='CfgC.DreamBase' },
    ["TbCNPCFunc"] = { name='TbCNPCFunc', file='cfgc_tbcnpcfunc', mode='map', index='Id', value_type='CfgC.NPCFunc' },
    ["TbOperateControl"] = { name='TbOperateControl', file='control_tboperatecontrol', mode='map', index='OperateId', value_type='Control.OperateControl' },
    ["TbFuncBase"] = { name='TbFuncBase', file='func_tbfuncbase', mode='map', index='FuncId', value_type='Func.FuncBase' },
}

-- * 组合key
---@param tKey table 可变参数
---@return string
local function combineKey(tKey)
    return "key_"..tableConcat(tKey, "_")
end

-- * 解析表格
local function parseTable(t, keys, srcDatas)
    t.AllTables = {}
    t.AllKeys = {}

    for _, data in pairs(srcDatas) do
        local tKey = {}
        for _, k in ipairs(keys) do
            tKey[#tKey + 1] = data[k]
        end
        local key = combineKey(tKey)
        t.AllKeys[key] = #t.AllTables + 1
        t.AllTables[t.AllKeys[key]] = data
    end
end

-- * 创建全部表格
---@param require function
---@return table 全部数据表格
local function createAllTables(require)
    ---@class GameConfig.AllTables
    local allTables = {}

    local TbCMapBase = function()
        ---@class TbCMapBase
        ---@field public AllTables CfgC.MapBase[] 全部配置
        ---@field public AllKeys table<string, integer> 全部Key
        local t = {
            AllTables = {},
            AllKeys = {},
        }
        parseTable(t,
            {
                "Id",
            },
            require("cfgc_tbcmapbase.lua")
        )

        ---@param Id integer @地图Id
        ---@return CfgC.MapBase?
        function t:GetData(Id,...)
            local tKey = {
                Id,
            }
            local key = combineKey(tKey)

            if self.AllKeys[key] == nil then
                return nil
            end

            return self.AllTables[self.AllKeys[key]]
        end

        return t
    end
    allTables.TbCMapBase = TbCMapBase()
    local TbCBattlefieldBase = function()
        ---@class TbCBattlefieldBase
        ---@field public AllTables CfgC.BattlefieldBase[] 全部配置
        ---@field public AllKeys table<string, integer> 全部Key
        local t = {
            AllTables = {},
            AllKeys = {},
        }
        parseTable(t,
            {
                "Id",
            },
            require("cfgc_tbcbattlefieldbase.lua")
        )

        ---@param Id integer @战场模式Id
        ---@return CfgC.BattlefieldBase?
        function t:GetData(Id,...)
            local tKey = {
                Id,
            }
            local key = combineKey(tKey)

            if self.AllKeys[key] == nil then
                return nil
            end

            return self.AllTables[self.AllKeys[key]]
        end

        return t
    end
    allTables.TbCBattlefieldBase = TbCBattlefieldBase()
    local TbCLanguage = function()
        ---@class TbCLanguage
        ---@field public AllTables CfgC.Language[] 全部配置
        ---@field public AllKeys table<string, integer> 全部Key
        local t = {
            AllTables = {},
            AllKeys = {},
        }
        parseTable(t,
            {
                "Id",
            },
            require("cfgc_tbclanguage.lua")
        )

        ---@param Id integer @文本Id，如果是
        ---@return CfgC.Language?
        function t:GetData(Id,...)
            local tKey = {
                Id,
            }
            local key = combineKey(tKey)

            if self.AllKeys[key] == nil then
                return nil
            end

            return self.AllTables[self.AllKeys[key]]
        end

        return t
    end
    allTables.TbCLanguage = TbCLanguage()
    local TbCNoticeText = function()
        ---@class TbCNoticeText
        ---@field public AllTables CfgC.NoticeText[] 全部配置
        ---@field public AllKeys table<string, integer> 全部Key
        local t = {
            AllTables = {},
            AllKeys = {},
        }
        parseTable(t,
            {
                "Id",
            },
            require("cfgc_tbcnoticetext.lua")
        )

        ---@param Id integer @提示Id，10000以下是系统的
        ---@return CfgC.NoticeText?
        function t:GetData(Id,...)
            local tKey = {
                Id,
            }
            local key = combineKey(tKey)

            if self.AllKeys[key] == nil then
                return nil
            end

            return self.AllTables[self.AllKeys[key]]
        end

        return t
    end
    allTables.TbCNoticeText = TbCNoticeText()
    local TbCDreamBase = function()
        ---@class TbCDreamBase
        ---@field public AllTables CfgC.DreamBase[] 全部配置
        ---@field public AllKeys table<string, integer> 全部Key
        local t = {
            AllTables = {},
            AllKeys = {},
        }
        parseTable(t,
            {
            },
            require("cfgc_tbcdreambase.lua")
        )

        ---@return CfgC.DreamBase?
        function t:GetData(...)
            local tKey = {
            }
            local key = combineKey(tKey)

            if self.AllKeys[key] == nil then
                return nil
            end

            return self.AllTables[self.AllKeys[key]]
        end

        return t
    end
    allTables.TbCDreamBase = TbCDreamBase()
    local TbCNPCFunc = function()
        ---@class TbCNPCFunc
        ---@field public AllTables CfgC.NPCFunc[] 全部配置
        ---@field public AllKeys table<string, integer> 全部Key
        local t = {
            AllTables = {},
            AllKeys = {},
        }
        parseTable(t,
            {
                "Id",
            },
            require("cfgc_tbcnpcfunc.lua")
        )

        ---@param Id integer @对应的NPCId
        ---@return CfgC.NPCFunc?
        function t:GetData(Id,...)
            local tKey = {
                Id,
            }
            local key = combineKey(tKey)

            if self.AllKeys[key] == nil then
                return nil
            end

            return self.AllTables[self.AllKeys[key]]
        end

        return t
    end
    allTables.TbCNPCFunc = TbCNPCFunc()
    local TbOperateControl = function()
        ---@class TbOperateControl
        ---@field public AllTables Control.OperateControl[] 全部配置
        ---@field public AllKeys table<string, integer> 全部Key
        local t = {
            AllTables = {},
            AllKeys = {},
        }
        parseTable(t,
            {
                "OperateId",
            },
            require("control_tboperatecontrol.lua")
        )

        ---@param OperateId integer @操作Id
        ---@return Control.OperateControl?
        function t:GetData(OperateId,...)
            local tKey = {
                OperateId,
            }
            local key = combineKey(tKey)

            if self.AllKeys[key] == nil then
                return nil
            end

            return self.AllTables[self.AllKeys[key]]
        end

        return t
    end
    allTables.TbOperateControl = TbOperateControl()
    local TbFuncBase = function()
        ---@class TbFuncBase
        ---@field public AllTables Func.FuncBase[] 全部配置
        ---@field public AllKeys table<string, integer> 全部Key
        local t = {
            AllTables = {},
            AllKeys = {},
        }
        parseTable(t,
            {
                "FuncId",
            },
            require("func_tbfuncbase.lua")
        )

        ---@param FuncId integer @功能Id
        ---@return Func.FuncBase?
        function t:GetData(FuncId,...)
            local tKey = {
                FuncId,
            }
            local key = combineKey(tKey)

            if self.AllKeys[key] == nil then
                return nil
            end

            return self.AllTables[self.AllKeys[key]]
        end

        return t
    end
    allTables.TbFuncBase = TbFuncBase()

    return allTables
end

return { enums = enums, beans = beans, tables = tables, createAllTables = createAllTables }

