
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------

local tableConcat = table.concat
local ipairs = ipairs
local pairs = pairs

local enums =
{
    ---@class ENetMessageId @网络消息ID
    ENetMessageId = { 
    -- * 玩家登录 参数 arg1 错误码 msgData Player_LoginInfo
    Player_Login=10000,
    -- * 请求匹配 参数 arg1 匹配模式 arg2 匹配开始时间
    MATCH_MatchReq=50000,
    -- * 请求匹配回复 参数 arg1 错误码
    MATCH_MatchRsp=50001,
    -- * 请求取消匹配 参数 无
    MATCH_CancelMatchReq=50002,
    -- * 请求取消匹配回复 参数 arg1 错误码
    MATCH_CancelMatchRsp=50003,
    -- * 匹配成功通知 参数 无
    MATCH_MatchSuccessNtf=50004,
    -- * 请求进入梦境 参数 arg1 梦境ID
    DREAM_EnterDreamReq=51000,
    -- * 请求进入梦境回复 参数 arg1 错误码
    DREAM_EnterDreamRsp=51001,
    -- * 请求离开梦境 参数 无
    DREAM_LeaveDreamReq=51002,
    -- * 请求离开梦境回复 参数 arg1 错误码
    DREAM_LeaveDreamRsp=51003,
    };

    ---@class ENetMessageId_Desc
    ENetMessageId_Desc = { 
    [10000]={ "Player_Login", "参数 arg1 错误码 msgData Player_LoginInfo" },
    [50000]={ "MATCH_MatchReq", "参数 arg1 匹配模式 arg2 匹配开始时间" },
    [50001]={ "MATCH_MatchRsp", "参数 arg1 错误码" },
    [50002]={ "MATCH_CancelMatchReq", "参数 无" },
    [50003]={ "MATCH_CancelMatchRsp", "参数 arg1 错误码" },
    [50004]={ "MATCH_MatchSuccessNtf", "参数 无" },
    [51000]={ "DREAM_EnterDreamReq", "参数 arg1 梦境ID" },
    [51001]={ "DREAM_EnterDreamRsp", "参数 arg1 错误码" },
    [51002]={ "DREAM_LeaveDreamReq", "参数 无" },
    [51003]={ "DREAM_LeaveDreamRsp", "参数 arg1 错误码" },
    };

}

---@class NetMessage.LubanBean
local beans = {}

---@return NetMessage.Player_LoginInfo
local createPlayer_LoginInfo = function()
    ---@class NetMessage.Player_LoginInfo  @玩家登录信息
    ---@field public DetailState integer @玩家详细状态，见 EPlayerDetailState
    ---@field public MatchMode integer @匹配模式，见 EMatchMode
    ---@field public MatchStartTime integer @匹配开始时间(GTM)
    return {
        DetailState =0,
        MatchMode =0,
        MatchStartTime =0,
    }
end
beans.createPlayer_LoginInfo = createPlayer_LoginInfo

local tables =
{
}

-- * 组合key
---@param tKey table 可变参数
---@return string
local function combineKey(tKey)
    return "key_"..tableConcat(tKey, "_")
end

-- * 解析表格
local function parseTable(t, keys, srcDatas)
    t.AllTables = {}
    t.AllKeys = {}

    for _, data in pairs(srcDatas) do
        local tKey = {}
        for _, k in ipairs(keys) do
            tKey[#tKey + 1] = data[k]
        end
        local key = combineKey(tKey)
        t.AllKeys[key] = #t.AllTables + 1
        t.AllTables[t.AllKeys[key]] = data
    end
end

-- * 创建全部表格
---@param require function
---@return table 全部数据表格
local function createAllTables(require)
    ---@class NetMessage.AllTables
    local allTables = {}


    return allTables
end

return { enums = enums, beans = beans, tables = tables, createAllTables = createAllTables }

